{
 "title": "Munchies",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Recipes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "munchies",
     "rawSql": "select count(*) from munchies.recipe_entity;"
    }
   ]
  },
  {
   "title": "Recent Recipe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "munchies",
     "rawSql": "SELECT title FROM recipe_entity order by updated_at desc limit 1;"
    }
   ]
  },
  {
   "title": "Total Labels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "munchies",
     "rawSql": "select count(*) from munchies.label_entity;"
    }
   ]
  },
  {
   "title": "Recent Label",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "munchies",
     "rawSql": "SELECT name FROM label_entity order by updated_at desc limit 1;"
    }
   ]
  }
 ]
}