{
 "title": "Music Collection",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Artists",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select count(*) from artistentity;"
    }
   ]
  },
  {
   "title": "Recent Artist",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select name from artistentity order by updatedat desc limit 1;"
    }
   ]
  },
  {
   "title": "Total Albums",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select count(*) from albumentity;"
    }
   ]
  },
  {
   "title": "Recent Album",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select name from albumentity order by updatedat desc limit 1;"
    }
   ]
  }
 ]
}