{
 "title": "Music Collection",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Artists",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select count(*) from artistentity;"
    }
   ]
  },
  {
   "title": "Recent Artist",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select name from artistentity order by updatedat desc limit 1;"
    }
   ]
  },
  {
   "title": "Artist attached Image",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "SELECT\n  CASE\n    WHEN filename IS NOT NULL THEN 'With image'\n    ELSE 'Without image'\n  END AS status,\n  COUNT(*) AS artists\nFROM artistentity\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "Album Count per Artist",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select artistentity.name as Artist, count(albumentity.id) as \"Total Albums\" from artistentity\nfull join albumentity on artistentity.id = albumentity.artistid\ngroup by artistentity.id\norder by \"Total Albums\" desc;"
    }
   ]
  },
  {
   "title": "Total Albums",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select count(*) from albumentity;"
    }
   ]
  },
  {
   "title": "Recent Album",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "select name from albumentity order by updatedat desc limit 1;"
    }
   ]
  },
  {
   "title": "Album attached Image",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "musiccollection",
     "rawSql": "SELECT\n  CASE\n    WHEN filename IS NOT NULL THEN 'With image'\n    ELSE 'Without image'\n  END AS status,\n  COUNT(*) AS artists\nFROM albumentity\nGROUP BY status;"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "keycloak",
     "rawSql": "select count(*) from user_entity;"
    }
   ]
  },
  {
   "title": "Recent User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "keycloak",
     "rawSql": "select first_name, last_name from user_entity order by created_timestamp desc limit 1;"
    }
   ]
  }
 ]
}